"""add_order_tables

Revision ID: ccf5a1156ecd
Revises: 110f1f08d4e4
Create Date: 2025-04-06 11:15:58.622903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccf5a1156ecd'
down_revision: Union[str, None] = '110f1f08d4e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('inventory_id', sa.String(length=32), nullable=False),
    sa.Column('order_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_order_inventory_id'), 'order', ['inventory_id'], unique=False)
    op.create_table('restaurantorder',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('restaurant_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'order_id', name='uix_restaurant_order')
    )
    op.create_index(op.f('ix_restaurantorder_order_id'), 'restaurantorder', ['order_id'], unique=False)
    op.create_index(op.f('ix_restaurantorder_restaurant_id'), 'restaurantorder', ['restaurant_id'], unique=False)
    op.create_unique_constraint(None, 'campaign', ['id'])
    op.create_unique_constraint(None, 'conversation', ['id'])
    op.create_unique_constraint(None, 'customer', ['id'])
    op.create_unique_constraint(None, 'inventory', ['id'])
    op.create_unique_constraint(None, 'messages', ['id'])
    op.create_unique_constraint(None, 'restaurant', ['id'])
    op.create_unique_constraint(None, 'restaurantcustomer', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurantcustomer', type_='unique')
    op.drop_constraint(None, 'restaurant', type_='unique')
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_constraint(None, 'inventory', type_='unique')
    op.drop_constraint(None, 'customer', type_='unique')
    op.drop_constraint(None, 'conversation', type_='unique')
    op.drop_constraint(None, 'campaign', type_='unique')
    op.drop_index(op.f('ix_restaurantorder_restaurant_id'), table_name='restaurantorder')
    op.drop_index(op.f('ix_restaurantorder_order_id'), table_name='restaurantorder')
    op.drop_table('restaurantorder')
    op.drop_index(op.f('ix_order_inventory_id'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
